nelmio_api_doc:
  documentation:
    components:
      schemas:
        Media:
          title: "Media"
          type: "object"
          properties:
            id:
              type: "integer"
            name:
              type: "string"
            description:
              type: "string"
            copyright:
              type: "string"
            url:
              type: "string"
            originalFilename:
              type: "string"
            folder:
              $ref: '#/components/schemas/Folder'
            contentType:
              type: "string"
            metadata:
              type: "string"
            filetype:
              type: "string"

        Folder:
          properties:
            id:
              type: "integer"
            name:
              type: "string"
            internalName:
              type: "string"
            rel:
              type: "string"
            parentId:
              type: "integer"
            lft:
              type: "integer"
            rgt:
              type: "integer"
            lvl:
              type: "integer"

        PostFolder:
          type: "object"
          properties:
            name:
              type: "string"
            internalName:
              type: "string"
            rel:
              type: "string"

        UploadMedia:
          title: "UploadMedia"
          type: "object"
          properties:
            content:
              type: "string"
            url:
              type: "string"
            name:
              type: "string"
            description:
              type: "string"
            copyRight:
              type: "string"
            folderId:
              type: "integer"
              default: 1

        putMedia:
          title: "UploadMedia"
          type: "object"
          properties:
            name:
              type: "string"
            description:
              type: "string"
            copyRight:
              type: "string"
            folderId:
              type: "integer"

        PaginatedMediaList:
          allOf:
            - $ref: '#/components/schemas/PaginatedResponse'
            - type: "object"
              properties:
                _embedded:
                  type: "object"
                  properties:
                    items:
                      type: "array"
                      items:
                        $ref: '#/components/schemas/Media'

        PaginatedFolderList:
          allOf:
            - $ref: '#/components/schemas/PaginatedResponse'
            - type: "object"
              properties:
                _embedded:
                  type: "object"
                  properties:
                    items:
                      type: "array"
                      items:
                        $ref: '#/components/schemas/Folder'
