nelmio_api_doc:
  documentation:
    components:
      schemas:
        PaginatedMenuList:
          allOf:
            - $ref: '#/components/schemas/PaginatedResponse'
            - type: "object"
              properties:
                _embedded:
                  type: "object"
                  properties:
                    items:
                      type: "array"
                      items:
                        $ref: '#/components/schemas/Menu'

        PaginatedMenuItemList:
          allOf:
            - $ref: '#/components/schemas/PaginatedResponse'
            - type: "object"
              properties:
                _embedded:
                  type: "object"
                  properties:
                    items:
                      type: "array"
                      items:
                        $ref: '#/components/schemas/MenuItem'

        PostMenu:
          title: "PostMenu"
          type: "object"
          properties:
            name:
              type: "string"
            locale:
              type: "string"
        PostMenuItem:
          title: "PostMenu"
          type: "object"
          properties:
            name:
              type: "string"
            locale:
              type: "string"
        PutMenuItem:
          title: "PostMenu"
          type: "object"
          properties:
            name:
              type: "string"
            locale:
              type: "string"
        Menu:
          title: "Menu"
          type: "object"
          properties:
            id:
              type: "integer"
            name:
              type: "string"
            locale:
              type: "string"

        MenuItem:
          title: "MenuItem"
          type: "object"
          properties:
            id:
              type: "integer"
            menu:
              $ref: '#/components/schemas/Folder'
            nodeTranslation:
              $ref: '#/components/schemas/NodeTranslation'
            type:
              type: "string"
            title:
              type: "string"
            url:
              type: "string"
            newWindow:
              type: "boolean"
            lft:
              type: "integer"
            rgt:
              type: "integer"
            lvl:
              type: "integer"
