services:
  kunstmaan_rest_core.service.data_transformer:
    class: Kunstmaan\Rest\CoreBundle\Service\DataTransformerService

  kunstmaan_rest_core.helper.controller.paginator:
    class: Kunstmaan\Rest\CoreBundle\Helper\Controller\Paginator
    public: true
    arguments:
      - '@request_stack'

  kunstmaan_rest_core.api_authenticator:
    class: Kunstmaan\Rest\CoreBundle\Security\ApiKeyAuthenticator
    arguments:
      - '@doctrine.orm.entity_manager'
      - '%fos_user.model.user.class%'
      - '%kunstmaan_rest_core.authentication.rest_header%'

  jms_serializer.object_constructor:
    alias: jms_serializer.doctrine_object_constructor
    public: false

  Kunstmaan\Rest\CoreBundle\Serializer\JMS\Expression\ArrayFunctionsProvider:
    tags:
      - jms.expression.function_provider

  nelmio_api_doc.controller.swagger:
    class: Kunstmaan\Rest\CoreBundle\Controller\DocumentationController
    public: true
    arguments:
      - '@nelmio_api_doc.generator_locator'
      - '%kunstmaan_rest_core.authentication.rest_header%'

  Kunstmaan\Rest\CoreBundle\Controller\AuthenticationController:
    public: true
    calls:
      - [ setContainer, [ '@service_container' ] ]
    tags: ['controller.service_arguments']
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@event_dispatcher'
      - '%fos_user.model.user.class%'

  nelmio_api_doc.controller.swagger_ui:
    class: Kunstmaan\Rest\CoreBundle\Controller\SwaggerUiController
    public: true
    arguments:
      - '@nelmio_api_doc.generator_locator'
      - '@twig'
      - '%kunstmaan_rest_core.authentication.rest_header%'

parameters:
  fos_user.model.user.class: Kunstmaan\Rest\CoreBundle\Entity\RestUser
  kunstmaan_user_management.user_admin_list_configurator.class: Kunstmaan\Rest\CoreBundle\AdminList\RestUserAdminListConfigurator
  kunstmaan_rest_core.authentication.rest_header: 'X-Api-Key'
