nelmio_api_doc:
  documentation:
    components:
      schemas:
        PaginatedFormSubmissionList:
          allOf:
            - $ref: '#/components/schemas/PaginatedResponse'
            - type: "object"
              properties:
                _embedded:
                  type: "object"
                  properties:
                    items:
                      type: "array"
                      items:
                        $ref: '#/components/schemas/FormSubmission'

        FormSubmission:
          title: "FormSubmission"
          type: "object"
          properties:
            id:
              type: "integer"
            lang:
              type: "string"
            created:
              type: "string"
            ipAddress:
              type: "string"
            fields:
              type: "sting"
            node:
              type: "object"
