Kunstmaan\NodeBundle\Entity\Node:
  exclusion_policy: ALL

  properties:
    hiddenFromNav:
      expose: true
      groups: [Default, edit, create]
    internalName:
      expose: true
      groups: [Default, edit, create]
    refEntityName:
      expose: true
      groups: [Default, edit, create]
    parent:
      expose: true
      type: 'Kunstmaan\NodeBundle\Entity\Node'
      groups: [Default, create]
      max_depth: 1
    lft:
      expose: true
      groups: [Default, edit, create]
    rgt:
      expose: true
      groups: [Default, edit, create]
    lvl:
      expose: true
      groups: [Default, edit, create]

  relations:
    -
      rel: self
      href: expr('/api/nodes/' ~ object.getId())
      groups: [Default]
    -
      rel: node_translations
      href: expr('/api/nodes/' ~ object.getId() ~ '/translations')
      groups: [Default]
      embedded:
        content: expr(array_values(object.getNodeTranslations(true).toArray()))
    -
      rel: children
      href: expr('/api/nodes/' ~ object.getId() ~ '/children')
      groups: [Default]
      embedded:
        content: expr(array_values(object.getChildren().toArray()))
        exclusion:
          groups: [NodeWithChildren]
