Kunstmaan\NodeBundle\Entity\Node:
  exclusion_policy: ALL

  properties:
    hiddenFromNav:
      expose: true
      groups: [edit, create]
    internalName:
      expose: true
      groups: [edit, create]
    refEntityName:
      expose: true
      groups: [edit, create]
    parent:
      expose: true
      type: 'Kunstmaan\NodeBundle\Entity\Node'
      groups: [create]
    lft:
      expose: true
      groups: [edit, create]
    rgt:
      expose: true
      groups: [edit, create]
    lvl:
      expose: true
      groups: [edit, create]

  relations:
    -
      rel: self
      href: expr('/api/nodes/' ~ object.getId())
    -
      rel: node_translations
      href: expr('/api/nodes/' ~ object.getId() ~ '/translations')
      embedded:
          content: expr(object.getNodeTranslations())
    -
      rel: children
      href: expr('/api/nodes/' ~ object.getId() ~ '/children')
      embedded:
        content: expr(object.getChildren())
