Kunstmaan\Rest\NodeBundle\Model\ApiContext:
  exclusion_policy: ALL

  properties:
    name:
      expose: true
      type: string
      groups: [Default, edit, create]

    pageParts:
      expose: true
      type: 'ArrayCollection<Kunstmaan\Rest\NodeBundle\Model\ApiPagePart>'
      groups: [Default, edit, create]
