Kunstmaan\Rest\NodeBundle\Model\ApiPage:
  exclusion_policy: ALL

  properties:
    page:
      expose: true
      type: 'Kunstmaan\Rest\NodeBundle\Model\ApiEntity'
      groups: [Default, edit, create]

    node:
      expose: true
      type: 'Kunstmaan\NodeBundle\Entity\Node'
      groups: [Default, edit, create]

    seo:
      expose: true
      type: 'Kunstmaan\SeoBundle\Entity\Seo'
      groups: [Default, edit, create]

    author:
      expose: true
      type: 'Kunstmaan\ArticleBundle\Entity\AbstractAuthor'
      groups: [Default, edit, create]

    nodeTranslation:
      expose: true
      type: 'Kunstmaan\NodeBundle\Entity\NodeTranslation'
      groups: [Default, edit, create]
      serialized_name: node_translation

    nodeVersion:
      expose: true
      type: 'Kunstmaan\NodeBundle\Entity\NodeVersion'
      groups: [Default, edit]
      serialized_name: node_version

    pageTemplate:
      expose: true
      type: 'Kunstmaan\Rest\NodeBundle\Model\ApiPageTemplate'
      groups: [Default, edit, create]
      serialized_name: page_template
