Kunstmaan\Rest\NodeBundle\Model\ApiPageTemplate:
  exclusion_policy: ALL

  properties:
    name:
      expose: true
      type: string
      groups: [Default, edit, create]

    contexts:
      expose: true
      type: 'ArrayCollection<Kunstmaan\Rest\NodeBundle\Model\ApiContext>'
      groups: [Default, edit, create]
