Kunstmaan\Rest\NodeBundle\Model\ApiPagePart:
  exclusion_policy: ALL

  properties:
    type:
      expose: true
      type: string
      groups: [Default, edit, create]

    data:
      expose: true
      type: 'Kunstmaan\PagePartBundle\Helper\PagePartInterface'
      groups: [Default, edit, create]
