nelmio_api_doc:
  documentation:
    components:
      schemas:
        Node:
          title: "Node"
          type: "object"
          properties:
            id:
              type: "integer"
            hidden_from_nav:
              type: "boolean"
            ref_entity_name:
              type: "string"
            internal_name:
              type: "string"
            slug:
              type: "string"
            url:
              type: "string"
            lft:
              type: "integer"
            rgt:
              type: "integer"
            lvl:
              type: "integer"

        NodeTranslation:
          properties:
            title:
              type: "string"
            lang:
              type: "string"
            online:
              type: "boolean"

        ApiPage:
          title: "Page"
          type: "object"
          properties:
            page:
              $ref: '#/components/schemas/ApiEntity'
            pageTemplate:
              $ref: '#/components/schemas/ApiPageTemplate'
            node:
              $ref: '#/components/schemas/PostNode'
            seo:
              $ref: '#/components/schemas/Seo'
            author:
              $ref: '#/components/schemas/Author'
            nodeTranslation:
              $ref: '#/components/schemas/PostNodeTranslation'

        Seo:
          title: "Seo"
          type: "object"
          properties:
            metaTitle:
              type: string
            metaDescription:
              type: string
            metaAuthor:
              type: string
            metaRobots:
              type: string
            ogType:
              type: string
            ogTitle:
              type: string
            ogDescription:
              type: string
            extraMetaData:
              type: string
            ogImage:
              $ref: '#/components/schemas/Media'

        GetNode:
          allOf:
            - $ref: '#/components/schemas/Node'
          properties:
            parent:
              type: "object"
              allOf:
                - $ref: '#/components/schemas/Node'
            _embedded:
              type: object
              properties:
                node_translations:
                  type: array
                  items:
                    $ref: '#/components/schemas/GetNodeTranslation'
                children:
                  type: array
                  items:
                    $ref: '#/components/schemas/GetNode'

        PostNode:
          allOf:
            - $ref: '#/components/schemas/Node'
          properties:
            parent:
              type: "object"
              allOf:
                - $ref: '#/components/schemas/Node'

        GetNodeTranslation:
          allOf:
            - $ref: '#/components/schemas/NodeTranslation'
          properties:
            id:
              type: "integer"
            weight:
              type: "integer"
            created:
              type: "string"
              format: "date-time"
            updated:
              type: "string"
              format: "date-time"

        PostNodeTranslation:
          allOf:
            - $ref: '#/components/schemas/NodeTranslation'

        NodeVersion:
          title: "nodeVersion"
          type: "object"
          properties:
            id:
              type: "integer"
            owner:
              type: "id"
            ref_id:
              type: "integer"
            ref_entity_name:
              type: "string"

        NestedNode:
          type: object
          properties:
            id:
              type: "integer"
            lft:
              type: "integer"
            rgt:
              type: "integer"
            lvl:
              type: "integer"
            nodeTranslations:
              type: array
              items:
                $ref: '#/components/schemas/NestedNodeTranslation'
            __children:
              type: array
              items:
                $ref: '#/components/schemas/NestedNode'

        NestedNodeTranslation:
          type: object
          properties:
            id:
              type: integer
            lang:
              type: string
            title:
              type: string
            slug:
              type: string
            created:
              type: string
              format: "date-time"
            updated:
              type: string
              format: "date-time"

        NestedNodeList:
          type: array
          items:
            $ref: '#/components/schemas/NestedNode'

        PaginatedNodeList:
          allOf:
            - $ref: '#/components/schemas/PaginatedResponse'
            - type: "object"
              properties:
                _embedded:
                  type: "object"
                  properties:
                    items:
                      type: "array"
                      items:
                        $ref: '#/components/schemas/GetNode'

        ApiEntity:
          title: "ApiEntity"
          type: "object"
          properties:
            type:
              type: "string"
              example: 'Kunstmaan\SomeBundle\Entity\Pages\HomePage'
            data:
              type: "object"

        ApiPagePart:
          title: "ApiPagePart"
          type: "object"
          properties:
            type:
              type: "string"
            data:
              type: "object"

        ApiContext:
          title: "ApiContext"
          type: "object"
          properties:
            name:
              type: "string"
            pageparts:
              type: "array"
              items:
                $ref: '#/components/schemas/ApiPagePart'

        ApiPageTemplate:
          title: "ApiPageTemplate"
          type: "object"
          properties:
            name:
              type: "string"
            contexts:
              type: "array"
              items:
                $ref: '#/components/schemas/ApiContext'

        GetApiPage:
          allOf:
            - $ref: '#/components/schemas/ApiPage'
          properties:
            nodeVersion:
              type: "object"
              allOf:
                - $ref: '#/components/schemas/NodeVersion'

        PostApiPage:
          allOf:
            - $ref: '#/components/schemas/ApiPage'

        PutApiPage:
          allOf:
            - $ref: '#/components/schemas/ApiPage'
